### ISSUE TITLE
Screen scrolling

### ISSUE THREAD

**Issue by samuelh2005** [vitaminac/minios#2]
It dose not really work for me,
When i press enter a few times so the input is at the bottom and press enter again, everything should scroll up, however it dose not, just stays at the bottom

**Comment by ajh123** [comment]
I did some debugging and it seems like it never gets past this if in screen.c
```
/* Advance the text cursor , scrolling the video buffer if necessary . */
int handle_scrolling(int cursor_offset)
{
    // If the cursor is within the screen , return it unmodified .
    if (cursor_offset < MAX_ROWS * MAX_COLS * 2)
    {
        return cursor_offset;
    }
    //Never gets past :(
```
